debug: true

# DJANGO ALLOWED_HOSTS
hosts:
  - 127.0.0.1
  - localhost

common:
  secret_key: "k$c4743!jegs=**x38e^eyz2t!spfc4udy_wvqxtgn&#^uostp"

# DJANGO DATABASE SETTINGS
db:
  engine: django.db.backends.postgresql
  host: 127.0.0.1
  port: 5432
  name: dictrainer
  user: dictrainer
  password: dictrainer

# CACHES
caches:
  redis:
    location:
      - 127.0.0.1:6379
    options:
      db: 0
      max_connections: 1000
      connection_pool_class_kwargs:
        max_connections: 50
        timeout: 20
