# Generated by Django 2.1.2 on 2018-10-27 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Message from user', max_length=128)),
                ('response', models.CharField(help_text='Response to user', max_length=128)),
                ('version', models.CharField(default='0.0.1', editable=False, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log entry',
                'verbose_name_plural': 'Log entries',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('wait_nothing', 'wait_nothing'), ('wait_input__create_dict', 'wait_input__create_dict')], default='wait_nothing', max_length=64)),
                ('current_dict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Dictionary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram profile',
                'verbose_name_plural': 'Telegram profiles',
            },
        ),
        migrations.AddField(
            model_name='telegramlogentry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bot.TelegramProfile'),
        ),
    ]
