# Generated by Django 2.1.2 on 2018-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessageEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('phrases', models.ManyToManyField(related_name='messages', to='dictionary.Phrase')),
            ],
            options={
                'verbose_name': 'Message-related entity',
                'verbose_name_plural': 'Message-related entities',
            },
        ),
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='telegramlogentry',
            name='text',
            field=models.TextField(help_text='Message from user', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='telegrammessageentity',
            unique_together={('chat_id', 'message_id')},
        ),
        migrations.AlterIndexTogether(
            name='telegrammessageentity',
            index_together={('chat_id', 'message_id')},
        ),
    ]
