# Generated by Django 2.1.2 on 2018-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20181029_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlogentry',
            name='text_length',
            field=models.IntegerField(default=0),
        ),
    ]
