# Generated by Django 2.1.2 on 2018-10-27 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
                ('editors', models.ManyToManyField(blank=True, related_name='editable_dictionaries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, related_name='readable_dictionaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
                'ordering': ('name', 'user'),
            },
        ),
        migrations.CreateModel(
            name='DictionaryUserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('training', 'training'), ('total', 'total')], max_length=32)),
                ('trained_count', models.IntegerField(default=0)),
                ('guessed_count', models.IntegerField(default=0)),
                ('dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='dictionary.Dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dictionary user stat',
                'verbose_name_plural': 'Dictionary user stats',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the language including dialect, script, etc.', max_length=50, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='The primary language code, used in file naming, etc. (e.g. pt_BR for Brazilian Portuguese.)', max_length=50, unique=True, verbose_name='Code')),
                ('code_aliases', models.CharField(blank=True, default='', help_text='A space-separated list of alternative locales.', max_length=100, null=True, verbose_name='Code aliases')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=255)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionary.Language')),
                ('user', models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='PhraseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dictionaries', models.ManyToManyField(related_name='phrase_groups', to='dictionary.Dictionary')),
                ('phrases', models.ManyToManyField(help_text='Ids of neighbour phrases (synonyms, translations)', related_name='phrase_groups', to='dictionary.Phrase')),
                ('user', models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phrase group',
                'verbose_name_plural': 'Phrase groups',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='PhraseUserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('trained_count', models.IntegerField(default=0)),
                ('guessed_count', models.IntegerField(default=0)),
                ('guessed_ratio', models.FloatField(default=0)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='dictionary.Phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_group_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phrase user stat',
                'verbose_name_plural': 'Phrase user stats',
            },
        ),
        migrations.AlterIndexTogether(
            name='language',
            index_together={('code',), ('code', 'code_aliases')},
        ),
        migrations.AlterUniqueTogether(
            name='phraseuserstat',
            unique_together={('user', 'phrase')},
        ),
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together={('lang', 'user', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='dictionaryuserstat',
            unique_together={('user', 'dict', 'kind')},
        ),
        migrations.AlterUniqueTogether(
            name='dictionary',
            unique_together={('name', 'user')},
        ),
    ]
