# Generated by Django 2.1.2 on 2018-10-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the language including dialect, script, etc.', max_length=50, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='The primary language code, used in file naming, etc. (e.g. pt_BR for Brazilian Portuguese.)', max_length=50, unique=True, verbose_name='Code')),
                ('code_aliases', models.CharField(blank=True, default='', help_text='A space-separated list of alternative locales.', max_length=100, null=True, verbose_name='Code aliases')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.AlterIndexTogether(
            name='language',
            index_together={('code', 'code_aliases'), ('code',)},
        ),
    ]
