# Generated by Django 2.1.2 on 2018-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20181015_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasealias',
            name='phrases',
        ),
        migrations.AddField(
            model_name='phrasealias',
            name='phrases',
            field=models.ManyToManyField(help_text='Ids of neighbour phrases (synonyms, translations)', related_name='phrase_aliases', to='dictionary.Phrase'),
        ),
    ]
